### PR TITLE
General fix

### PR DESCRIPTION
**Pull request by thorsummoner**
Normalized python files, 
ported code to python3
debugged (on windows)

I renamed some files, git didn't catch the rename for me, I didn't delete any functional code.

### CODE REVIEW

**Comment by EndlesslyCurious** [comment]
I'm actually going to stop using Github, would you be interested in taking over this repo? I can transfer ownership to you.

**Comment by thorsummoner** [comment]
Yes

**Comment by EndlesslyCurious** [comment]
Great, it looks like you need to delete your local report before I can
transfer the original repo to you. At least if I understand the doces
right: https://help.github.com/articles/transferring-a-repository/

On 20 March 2015 at 16:11, thorsummoner <notifications@github.com> wrote:

> Yes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EndlesslyCurious/Duplicate-Files/pull/3#issuecomment-84039918>
> .
>



-- 

/daniel

**Comment by EndlesslyCurious** [comment]
Delete your fork even. That way your repo would be the root of the fork
network once I transfer the repo from my account to your account.

Let me know as I'll be deleting my account in the next week or so.

On 22 March 2015 at 17:51, Daniel Brown <Daniel@endlesslycurious.com> wrote:

> Great, it looks like you need to delete your local report before I can
> transfer the original repo to you. At least if I understand the doces
> right: https://help.github.com/articles/transferring-a-repository/
>
> On 20 March 2015 at 16:11, thorsummoner <notifications@github.com> wrote:
>
>> Yes
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/EndlesslyCurious/Duplicate-Files/pull/3#issuecomment-84039918>
>> .
>>
>
>
>
> --
>
> /daniel
>



-- 

/daniel

**Comment by thorsummoner** [comment]
I've moved my old one, that should make the namespace available. If it still forbids you let me know as I'll have made a backup by tonight.

**Comment by EndlesslyCurious** [comment]
Hmm it still gives me the same error 'thorsummoner already has a repository
in the EndlesslyCurious/Duplicate-Files network'

On 25 March 2015 at 17:08, thorsummoner <notifications@github.com> wrote:

> I've moved my old one, that should make the namespace available. If it
> still forbids you let me know as I'll have made a backup by tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EndlesslyCurious/Duplicate-Files/pull/3#issuecomment-86097522>
> .
>



-- 

/daniel

**Comment by thorsummoner** [comment]
Mmk, repo truely deleted from my github account. Ready for the next try!
Thank you so much for working with me on this, I would be dissapointed to lose this base.

I think in the future I will be looking at offereing multiple hashing algorithms. I'm pleased by xxhash's speed.

When I take over this project, is there a specific platform/version of python you would like I ensure compatibility with?

**Comment by EndlesslyCurious** [comment]
No problem, I just like to see the code to live on even if I'm not active
on github any more. Please feel free to develop it as you like, I mostly
use Python 2.7 at work but don't let that hold you back if you want to port
it to 3.

On 25 March 2015 at 23:41, thorsummoner <notifications@github.com> wrote:

> Mmk, repo truely deleted from my github account. Ready for the next try!
> Thank you so much for working with me on this, I would be dissapointed to
> lose this base.
>
> I think in the future I will be looking at offereing multiple hashing
> algorithms. I'm pleased by xxhash's speed.
>
> When I take over this project, is there a specific platform/version of
> python you would like I ensure compatibility with?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EndlesslyCurious/Duplicate-Files/pull/3#issuecomment-86240391>
> .
>



-- 

/daniel

**Pull request closed without merging**
